-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."BENEFICIOS"
(
    id bigint NOT NULL,
    nombre_beneficio character(50)[] COLLATE pg_catalog."default",
    is_covered bigint,
    quant_limit_on_svc bigint,
    explicacion character(150)[] COLLATE pg_catalog."default",
    is_excel_from_inn_moop bigint,
    is_excel_from_onn_moop bigint,
    plan_id character(50)[] COLLATE pg_catalog."default",
    CONSTRAINT "BENEFICIOS_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."CANTIDADES"
(
    id bigint NOT NULL,
    limite bigint,
    unidad_limite character(50)[] COLLATE pg_catalog."default",
    beneficio_id bigint,
    CONSTRAINT "CANTIDADES_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."COSTOS"
(
    id bigint NOT NULL,
    beneficio_id bigint,
    copay_inn_tier1 character(1)[] COLLATE pg_catalog."default",
    copay_inn_tier2 character(1)[] COLLATE pg_catalog."default",
    copay_out_of_net character(1)[] COLLATE pg_catalog."default",
    coins_inn_tier1 bigint,
    coins_inn_tier2 bigint,
    cost_out_of_net bigint,
    CONSTRAINT "COSTOS_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."EDADES"
(
    id bigint NOT NULL,
    estado_id bigint,
    edad character(50)[] COLLATE pg_catalog."default",
    cantidad_edades bigint,
    CONSTRAINT edades_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."EDADES_SEGUROS"
(
    id bigint NOT NULL,
    plan_id character(30)[] COLLATE pg_catalog."default",
    edad character(30)[] COLLATE pg_catalog."default",
    CONSTRAINT "EDADES_SEGUROS_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."EDUCACION"
(
    id bigint NOT NULL,
    edad_id bigint,
    grado character(50)[] COLLATE pg_catalog."default",
    cantidad_educacion bigint,
    CONSTRAINT "EDUCACION_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ESTADOS"
(
    id bigint NOT NULL,
    nombre character(50)[] COLLATE pg_catalog."default",
    CONSTRAINT "ESTADOS_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ESTADOS_CIVILES"
(
    id bigint NOT NULL,
    edad_id bigint,
    estado_civil character(50)[] COLLATE pg_catalog."default",
    cantidad_civil bigint,
    CONSTRAINT "ESTADOS_CIVILES_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."ETNIAS"
(
    id bigint NOT NULL,
    edad_id bigint,
    etnia character(50)[] COLLATE pg_catalog."default",
    cantidad_etnias bigint,
    CONSTRAINT "ETNIAS_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."FECHAS_TASAS"
(
    id bigint NOT NULL,
    edad_seguro_id bigint,
    fecha_efectiva character(15)[] COLLATE pg_catalog."default",
    fecha_expiracion character(15)[] COLLATE pg_catalog."default",
    CONSTRAINT "FECHAS_TASAS_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."HOGARES"
(
    id bigint NOT NULL,
    edad_id bigint,
    personas character(50)[] COLLATE pg_catalog."default",
    camtidad_hogares bigint,
    CONSTRAINT "HOGARES_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."INGRESOS"
(
    id bigint NOT NULL,
    edad_id bigint,
    ingreso character(1)[] COLLATE pg_catalog."default",
    cantidad_ingreso bigint,
    CONSTRAINT "INGRESOS_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."PLANES"
(
    id character(50)[] COLLATE pg_catalog."default" NOT NULL,
    estado_id bigint,
    nombre_estado character(50)[] COLLATE pg_catalog."default",
    nombre_plan character(50)[] COLLATE pg_catalog."default",
    tipo character(6)[] COLLATE pg_catalog."default",
    nivel_metal character(15)[] COLLATE pg_catalog."default",
    CONSTRAINT "PLANES_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TARIFAS_GRUPALES"
(
    id bigint NOT NULL,
    fechas_id bigint,
    tarifa_parejas double precision,
    beneficiario_un_dependiente double precision,
    beneficiario_dos_dependientes double precision,
    beneficiario_tres_mas_dependientes double precision,
    pareja_un_dependiente double precision,
    pareja_dos_dependientes double precision,
    pareja_tres_mas_dependientes double precision,
    CONSTRAINT "TARIFAS_GRUPALES_pkey" PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public."TARIFAS_INDIVIDUALES"
(
    id bigint NOT NULL,
    fechas_id bigint,
    tarifa double precision,
    CONSTRAINT "TARIFAS_INDIVIDUALES_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."BENEFICIOS"
    ADD CONSTRAINT fk_ben_cod_plan FOREIGN KEY (plan_id)
    REFERENCES public."PLANES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."CANTIDADES"
    ADD CONSTRAINT fk_can_cod_beneficios FOREIGN KEY (beneficio_id)
    REFERENCES public."BENEFICIOS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."COSTOS"
    ADD CONSTRAINT fk_cos_cod_beneficios FOREIGN KEY (beneficio_id)
    REFERENCES public."BENEFICIOS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."EDADES"
    ADD CONSTRAINT fk_eda_cod_estado FOREIGN KEY (estado_id)
    REFERENCES public."ESTADOS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."EDADES_SEGUROS"
    ADD CONSTRAINT fk_eda_seg_cod_planes FOREIGN KEY (plan_id)
    REFERENCES public."PLANES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."EDUCACION"
    ADD CONSTRAINT fk_edu_cod_edades FOREIGN KEY (edad_id)
    REFERENCES public."EDADES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ESTADOS_CIVILES"
    ADD CONSTRAINT fk_civ_cod_edades FOREIGN KEY (edad_id)
    REFERENCES public."EDADES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."ETNIAS"
    ADD CONSTRAINT fk_etn_cod_edades FOREIGN KEY (edad_id)
    REFERENCES public."EDADES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FECHAS_TASAS"
    ADD CONSTRAINT fk_fec_cod_edades_seg FOREIGN KEY (edad_seguro_id)
    REFERENCES public."EDADES_SEGUROS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."HOGARES"
    ADD CONSTRAINT fk_hog_cod_edades FOREIGN KEY (edad_id)
    REFERENCES public."EDADES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."INGRESOS"
    ADD CONSTRAINT fk_ing_cod_edades FOREIGN KEY (edad_id)
    REFERENCES public."EDADES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PLANES"
    ADD CONSTRAINT fk_pla_cod_estado FOREIGN KEY (estado_id)
    REFERENCES public."ESTADOS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TARIFAS_GRUPALES"
    ADD CONSTRAINT fk_tas_gru_cod_fechas FOREIGN KEY (fechas_id)
    REFERENCES public."FECHAS_TASAS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."TARIFAS_INDIVIDUALES"
    ADD CONSTRAINT fk_tas_ind_cod_fechas FOREIGN KEY (fechas_id)
    REFERENCES public."FECHAS_TASAS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;