-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public."BENEFICIOS";

CREATE TABLE IF NOT EXISTS public."BENEFICIOS"
(
    id bigint NOT NULL,
    nombre_beneficio varchar(150) COLLATE pg_catalog."default",
    is_covered varchar(15) COLLATE pg_catalog."default",
    quant_limit_on_svc varchar(15) COLLATE pg_catalog."default",
    is_excl_from_inn_moop varchar(15) COLLATE pg_catalog."default",
    is_excl_from_onn_moop varchar(15) COLLATE pg_catalog."default",
    plan_id varchar(50) COLLATE pg_catalog."default",
    CONSTRAINT "BENEFICIOS_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."CENSO";

create table if not exists public."CENSO"
(
    id                    bigint       not null
        primary key,
    rango_edades          varchar(50),
    cantidad_rango_edades bigint,
    grado                 varchar(50),
    cantidad_grado        bigint,
    estado_civil          varchar(50),
    cantidad_estado_civil bigint,
    hogar                 varchar(50),
    cantidad_hogar        bigint,
    ingreso               varchar(100),
    cantidad_ingreso      bigint,
    estado                varchar(50),
    poblacion             bigint
);



DROP TABLE IF EXISTS public."EDADES_SEGUROS";

CREATE TABLE IF NOT EXISTS public."EDADES_SEGUROS"
(
    id bigint NOT NULL,
    plan_id varchar(50) COLLATE pg_catalog."default",
    edad varchar(15) COLLATE pg_catalog."default",
    CONSTRAINT "EDADES_SEGUROS_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."FECHAS_TASAS";

CREATE TABLE IF NOT EXISTS public."FECHAS_TASAS"
(
    id bigint NOT NULL,
    edad_seguro_id bigint,
    fecha_efectiva varchar(15) COLLATE pg_catalog."default",
    fecha_expiracion varchar(15) COLLATE pg_catalog."default",
    CONSTRAINT "FECHAS_TASAS_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."PERFILES";

CREATE TABLE IF NOT EXISTS public."PERFILES"
(
    id bigint NOT NULL,
    id_censo bigint,
    edad varchar(100) COLLATE pg_catalog."default",
    grado varchar(100) COLLATE pg_catalog."default",
    estado_civil varchar(50) COLLATE pg_catalog."default",
    hogar varchar(50) COLLATE pg_catalog."default",
    ingreso varchar(100) COLLATE pg_catalog."default",
    estado varchar(50) COLLATE pg_catalog."default",
    CONSTRAINT "PERFILES_pkey" PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public."PLANES";

CREATE TABLE IF NOT EXISTS public."PLANES"
(
    id varchar(25) COLLATE pg_catalog."default" NOT NULL,
    nombre_plan varchar(200) COLLATE pg_catalog."default",
    tipo varchar(10) COLLATE pg_catalog."default",
    nivel_metal varchar(15) COLLATE pg_catalog."default",
    nombre_proveedor varchar(100) COLLATE pg_catalog."default",
    estado varchar(50) COLLATE pg_catalog."default",
    id_perfil bigint,
    CONSTRAINT "PLANES_pkey" PRIMARY KEY (id)
);


DROP TABLE IF EXISTS public."TASAS_INDIVIDUALES";

CREATE TABLE IF NOT EXISTS public."TASAS_INDIVIDUALES"
(
    id bigint NOT NULL,
    fechas_id bigint,
    tarifa double precision,
    CONSTRAINT "TASAS_INDIVIDUALES_pkey" PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public."BENEFICIOS"
    ADD CONSTRAINT fk_beneficios_cod_planes FOREIGN KEY (plan_id)
    REFERENCES public."PLANES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;




ALTER TABLE IF EXISTS public."EDADES_SEGUROS"
    ADD CONSTRAINT fk_edads_cod_planes FOREIGN KEY (plan_id)
    REFERENCES public."PLANES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."FECHAS_TASAS"
    ADD CONSTRAINT fk_fechas_cod_edads FOREIGN KEY (edad_seguro_id)
    REFERENCES public."EDADES_SEGUROS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PERFILES"
    ADD CONSTRAINT fk_perfiles_censo FOREIGN KEY (id_censo)
    REFERENCES public."CENSO" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."PLANES"
    ADD CONSTRAINT fk_planes_cod_perfiles FOREIGN KEY (id_perfil)
    REFERENCES public."PERFILES" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

ALTER TABLE IF EXISTS public."TASAS_INDIVIDUALES"
    ADD CONSTRAINT fk_tarifasi_cod_fechas FOREIGN KEY (fechas_id)
    REFERENCES public."FECHAS_TASAS" (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;